# Generated by Django 6.0.4 on 2026-05-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('indirizzo', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ristorante',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('In elaborazione', 'in elaborazione'), ('In preparazione', 'in preparazione'), ('In transito', 'in transito'), ('Consegnato', 'consegnato')], default='In preparazione', max_length=50)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='api.cliente')),
                ('ristorante_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='api.ristorante')),
            ],
        ),
        migrations.CreateModel(
            name='OrdineDettaglio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantita', models.IntegerField()),
                ('ordine_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ordine')),
                ('piatto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettagli_ordine', to='api.piatto')),
            ],
        ),
        migrations.AddField(
            model_name='ristorante',
            name='tipologia_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ristoranti', to='api.tipologia'),
        ),
    ]
