# Generated by Django 6.0.4 on 2026-05-06 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cliente_id_alter_ordine_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinedettaglio',
            name='quantita',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
