# Generated by Django 6.0.4 on 2026-05-06 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_ristoranti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piatto',
            name='ristorante_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piatti', to='gestione_ristoranti.ristorante'),
        ),
    ]
