# Generated by Django 6.0.4 on 2026-05-06 12:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione_ristoranti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('indirizzo', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('In elaborazione', 'in elaborazione'), ('In preparazione', 'in preparazione'), ('In transito', 'in transito'), ('Consegnato', 'consegnato')], default='In preparazione', max_length=50)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='gestione_ordini.cliente')),
                ('ristorante_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='gestione_ristoranti.ristorante')),
            ],
        ),
        migrations.CreateModel(
            name='OrdineDettaglio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ordine_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestione_ordini.ordine')),
                ('piatto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettagli_ordine', to='gestione_ristoranti.piatto')),
            ],
        ),
    ]
