# Generated by Django 6.0.4 on 2026-05-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_ordini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='testata',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
